### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Bia10** [edgarssults/Bannerboard#1]
Hey, nice job there, i have been using base of this project as bootstrap for my own game tracker.

However i have noticed some weird behavior:

Moving widgets around is very sluggish.
When moving widgets over another widget the application freezes, which in turn causes the websocket server to spam timeout exceptions.

Have you also encountered these problems?

**Comment by edgarssults** [comment]
Yes, this is a problem with the grid library. I'm thinking of replacing it with something else, but there aren't many Blazor options available. Adjusting a JS library to work with Blazor is possible with interop, but it would take a while to implement. So I haven't replaced it yet.

My recommendation is to move the widgets slowly and try not to overlap them to prevent the freezing until I can come up with a solution.

**Comment by Bia10** [comment]
oh dang, maybe i guess ill hack around that by enforcing some layout presets.

btw another thing i noticed is your using bootstrap 4 is there any reason why ur not using bootstrap 5?

**Comment by edgarssults** [comment]
Either Bootstrap 5 wasn't released when I started working on it or the Blazorise library didn't support it at the time. I don't remember. I tried updating the Blazorise libraries recently, but they changed the API in 1.0 and the charts broke, so I've put that off for a while.

**Comment by edgarssults** [comment]
Updated the grid library, it seems to have fixed the freezes.
