### ISSUE TITLE
Bannerlord crashes when moving on campaign map

### ISSUE THREAD

**Issue by Stache73** [edgarssults/Bannerboard#4]
Bannerlord crashes when moving on campaign map. 
Bannerboard is the involved module in the crash report: 

https://report.butr.link/203665.html

**Comment by edgarssults** [comment]
Thanks, I'll look into it.

**Comment by edgarssults** [comment]
Added additional exception handling around the hero widget updates. I'm not sure what exactly was null there, possibly the list of tracked heroes. Released with mod v0.4.1.
