### ISSUE TITLE
Could not establish a connection to the server. 

### ISSUE THREAD

**Issue by IAmSanyka** [edgarssults/Bannerboard#5]
Whenever I try to connect to the server I get this message. "Could not establish a connection to the server. Refresh the page once you've loaded a campaign." Is there anything I can do about it? I tried to turn off anti-virus, adblockers, tried Opera and Chrome. Same thing every time. However, in-game i get the message the server is running. It may be important that i'm on Xbox GamePass version.  I got bunch of other mods, too.
I posted it on Nexus as well.

**Comment by edgarssults** [comment]
Thank you for reaching out. I don't check the Nexus forums that often anymore.

I haven't tested the mod with the GamePass version. It might be doing some sandboxing of the game and preventing the connection. If that's the case, there's not much I can do apart from routing the connection through the cloud, which I don't currently plan on implementing. Im sorry that you won't be able to use the mod.
________________________________
From: IAmSanyka ***@***.***>
Sent: Wednesday, September 20, 2023 5:55:56 AM
To: edgarssults/Bannerboard ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [edgarssults/Bannerboard] Could not establish a connection to the server. (Issue #5)


Whenever I try to connect to the server I get this message. "Could not establish a connection to the server. Refresh the page once you've loaded a campaign." Is there anything I can do about it? I tried to turn off anti-virus, adblockers, tried Opera and Chrome. Same thing every time. However, in-game i get the message the server is running. It may be important that i'm on Xbox GamePass version. I got bunch of other mods, too.
I posted it on Nexus as well.

**Comment by IAmSanyka** [comment]
Ok, I got it. Thanks for the reply nonetheless. Best of luck!
